// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: examples/proto/examplepb/wrappers.proto

package examplepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf6 "github.com/golang/protobuf/ptypes/wrappers"
import google_protobuf2 "github.com/golang/protobuf/ptypes/empty"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = google_protobuf6.BytesValue{}
var _ = google_protobuf2.Empty{}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for WrappersService service

type WrappersService interface {
	Create(ctx context.Context, in *Wrappers, opts ...client.CallOption) (*Wrappers, error)
	CreateStringValue(ctx context.Context, in *google_protobuf6.StringValue, opts ...client.CallOption) (*google_protobuf6.StringValue, error)
	CreateInt32Value(ctx context.Context, in *google_protobuf6.Int32Value, opts ...client.CallOption) (*google_protobuf6.Int32Value, error)
	CreateInt64Value(ctx context.Context, in *google_protobuf6.Int64Value, opts ...client.CallOption) (*google_protobuf6.Int64Value, error)
	CreateFloatValue(ctx context.Context, in *google_protobuf6.FloatValue, opts ...client.CallOption) (*google_protobuf6.FloatValue, error)
	CreateDoubleValue(ctx context.Context, in *google_protobuf6.DoubleValue, opts ...client.CallOption) (*google_protobuf6.DoubleValue, error)
	CreateBoolValue(ctx context.Context, in *google_protobuf6.BoolValue, opts ...client.CallOption) (*google_protobuf6.BoolValue, error)
	CreateUInt32Value(ctx context.Context, in *google_protobuf6.UInt32Value, opts ...client.CallOption) (*google_protobuf6.UInt32Value, error)
	CreateUInt64Value(ctx context.Context, in *google_protobuf6.UInt64Value, opts ...client.CallOption) (*google_protobuf6.UInt64Value, error)
	CreateBytesValue(ctx context.Context, in *google_protobuf6.BytesValue, opts ...client.CallOption) (*google_protobuf6.BytesValue, error)
	CreateEmpty(ctx context.Context, in *google_protobuf2.Empty, opts ...client.CallOption) (*google_protobuf2.Empty, error)
}

type wrappersService struct {
	c    client.Client
	name string
}

func NewWrappersService(name string, c client.Client) WrappersService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "grpc.gateway.examples.examplepb"
	}
	return &wrappersService{
		c:    c,
		name: name,
	}
}

func (c *wrappersService) Create(ctx context.Context, in *Wrappers, opts ...client.CallOption) (*Wrappers, error) {
	req := c.c.NewRequest(c.name, "WrappersService.Create", in)
	out := new(Wrappers)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrappersService) CreateStringValue(ctx context.Context, in *google_protobuf6.StringValue, opts ...client.CallOption) (*google_protobuf6.StringValue, error) {
	req := c.c.NewRequest(c.name, "WrappersService.CreateStringValue", in)
	out := new(google_protobuf6.StringValue)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrappersService) CreateInt32Value(ctx context.Context, in *google_protobuf6.Int32Value, opts ...client.CallOption) (*google_protobuf6.Int32Value, error) {
	req := c.c.NewRequest(c.name, "WrappersService.CreateInt32Value", in)
	out := new(google_protobuf6.Int32Value)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrappersService) CreateInt64Value(ctx context.Context, in *google_protobuf6.Int64Value, opts ...client.CallOption) (*google_protobuf6.Int64Value, error) {
	req := c.c.NewRequest(c.name, "WrappersService.CreateInt64Value", in)
	out := new(google_protobuf6.Int64Value)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrappersService) CreateFloatValue(ctx context.Context, in *google_protobuf6.FloatValue, opts ...client.CallOption) (*google_protobuf6.FloatValue, error) {
	req := c.c.NewRequest(c.name, "WrappersService.CreateFloatValue", in)
	out := new(google_protobuf6.FloatValue)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrappersService) CreateDoubleValue(ctx context.Context, in *google_protobuf6.DoubleValue, opts ...client.CallOption) (*google_protobuf6.DoubleValue, error) {
	req := c.c.NewRequest(c.name, "WrappersService.CreateDoubleValue", in)
	out := new(google_protobuf6.DoubleValue)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrappersService) CreateBoolValue(ctx context.Context, in *google_protobuf6.BoolValue, opts ...client.CallOption) (*google_protobuf6.BoolValue, error) {
	req := c.c.NewRequest(c.name, "WrappersService.CreateBoolValue", in)
	out := new(google_protobuf6.BoolValue)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrappersService) CreateUInt32Value(ctx context.Context, in *google_protobuf6.UInt32Value, opts ...client.CallOption) (*google_protobuf6.UInt32Value, error) {
	req := c.c.NewRequest(c.name, "WrappersService.CreateUInt32Value", in)
	out := new(google_protobuf6.UInt32Value)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrappersService) CreateUInt64Value(ctx context.Context, in *google_protobuf6.UInt64Value, opts ...client.CallOption) (*google_protobuf6.UInt64Value, error) {
	req := c.c.NewRequest(c.name, "WrappersService.CreateUInt64Value", in)
	out := new(google_protobuf6.UInt64Value)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrappersService) CreateBytesValue(ctx context.Context, in *google_protobuf6.BytesValue, opts ...client.CallOption) (*google_protobuf6.BytesValue, error) {
	req := c.c.NewRequest(c.name, "WrappersService.CreateBytesValue", in)
	out := new(google_protobuf6.BytesValue)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrappersService) CreateEmpty(ctx context.Context, in *google_protobuf2.Empty, opts ...client.CallOption) (*google_protobuf2.Empty, error) {
	req := c.c.NewRequest(c.name, "WrappersService.CreateEmpty", in)
	out := new(google_protobuf2.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WrappersService service

type WrappersServiceHandler interface {
	Create(context.Context, *Wrappers, *Wrappers) error
	CreateStringValue(context.Context, *google_protobuf6.StringValue, *google_protobuf6.StringValue) error
	CreateInt32Value(context.Context, *google_protobuf6.Int32Value, *google_protobuf6.Int32Value) error
	CreateInt64Value(context.Context, *google_protobuf6.Int64Value, *google_protobuf6.Int64Value) error
	CreateFloatValue(context.Context, *google_protobuf6.FloatValue, *google_protobuf6.FloatValue) error
	CreateDoubleValue(context.Context, *google_protobuf6.DoubleValue, *google_protobuf6.DoubleValue) error
	CreateBoolValue(context.Context, *google_protobuf6.BoolValue, *google_protobuf6.BoolValue) error
	CreateUInt32Value(context.Context, *google_protobuf6.UInt32Value, *google_protobuf6.UInt32Value) error
	CreateUInt64Value(context.Context, *google_protobuf6.UInt64Value, *google_protobuf6.UInt64Value) error
	CreateBytesValue(context.Context, *google_protobuf6.BytesValue, *google_protobuf6.BytesValue) error
	CreateEmpty(context.Context, *google_protobuf2.Empty, *google_protobuf2.Empty) error
}

func RegisterWrappersServiceHandler(s server.Server, hdlr WrappersServiceHandler, opts ...server.HandlerOption) error {
	type wrappersService interface {
		Create(ctx context.Context, in *Wrappers, out *Wrappers) error
		CreateStringValue(ctx context.Context, in *google_protobuf6.StringValue, out *google_protobuf6.StringValue) error
		CreateInt32Value(ctx context.Context, in *google_protobuf6.Int32Value, out *google_protobuf6.Int32Value) error
		CreateInt64Value(ctx context.Context, in *google_protobuf6.Int64Value, out *google_protobuf6.Int64Value) error
		CreateFloatValue(ctx context.Context, in *google_protobuf6.FloatValue, out *google_protobuf6.FloatValue) error
		CreateDoubleValue(ctx context.Context, in *google_protobuf6.DoubleValue, out *google_protobuf6.DoubleValue) error
		CreateBoolValue(ctx context.Context, in *google_protobuf6.BoolValue, out *google_protobuf6.BoolValue) error
		CreateUInt32Value(ctx context.Context, in *google_protobuf6.UInt32Value, out *google_protobuf6.UInt32Value) error
		CreateUInt64Value(ctx context.Context, in *google_protobuf6.UInt64Value, out *google_protobuf6.UInt64Value) error
		CreateBytesValue(ctx context.Context, in *google_protobuf6.BytesValue, out *google_protobuf6.BytesValue) error
		CreateEmpty(ctx context.Context, in *google_protobuf2.Empty, out *google_protobuf2.Empty) error
	}
	type WrappersService struct {
		wrappersService
	}
	h := &wrappersServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&WrappersService{h}, opts...))
}

type wrappersServiceHandler struct {
	WrappersServiceHandler
}

func (h *wrappersServiceHandler) Create(ctx context.Context, in *Wrappers, out *Wrappers) error {
	return h.WrappersServiceHandler.Create(ctx, in, out)
}

func (h *wrappersServiceHandler) CreateStringValue(ctx context.Context, in *google_protobuf6.StringValue, out *google_protobuf6.StringValue) error {
	return h.WrappersServiceHandler.CreateStringValue(ctx, in, out)
}

func (h *wrappersServiceHandler) CreateInt32Value(ctx context.Context, in *google_protobuf6.Int32Value, out *google_protobuf6.Int32Value) error {
	return h.WrappersServiceHandler.CreateInt32Value(ctx, in, out)
}

func (h *wrappersServiceHandler) CreateInt64Value(ctx context.Context, in *google_protobuf6.Int64Value, out *google_protobuf6.Int64Value) error {
	return h.WrappersServiceHandler.CreateInt64Value(ctx, in, out)
}

func (h *wrappersServiceHandler) CreateFloatValue(ctx context.Context, in *google_protobuf6.FloatValue, out *google_protobuf6.FloatValue) error {
	return h.WrappersServiceHandler.CreateFloatValue(ctx, in, out)
}

func (h *wrappersServiceHandler) CreateDoubleValue(ctx context.Context, in *google_protobuf6.DoubleValue, out *google_protobuf6.DoubleValue) error {
	return h.WrappersServiceHandler.CreateDoubleValue(ctx, in, out)
}

func (h *wrappersServiceHandler) CreateBoolValue(ctx context.Context, in *google_protobuf6.BoolValue, out *google_protobuf6.BoolValue) error {
	return h.WrappersServiceHandler.CreateBoolValue(ctx, in, out)
}

func (h *wrappersServiceHandler) CreateUInt32Value(ctx context.Context, in *google_protobuf6.UInt32Value, out *google_protobuf6.UInt32Value) error {
	return h.WrappersServiceHandler.CreateUInt32Value(ctx, in, out)
}

func (h *wrappersServiceHandler) CreateUInt64Value(ctx context.Context, in *google_protobuf6.UInt64Value, out *google_protobuf6.UInt64Value) error {
	return h.WrappersServiceHandler.CreateUInt64Value(ctx, in, out)
}

func (h *wrappersServiceHandler) CreateBytesValue(ctx context.Context, in *google_protobuf6.BytesValue, out *google_protobuf6.BytesValue) error {
	return h.WrappersServiceHandler.CreateBytesValue(ctx, in, out)
}

func (h *wrappersServiceHandler) CreateEmpty(ctx context.Context, in *google_protobuf2.Empty, out *google_protobuf2.Empty) error {
	return h.WrappersServiceHandler.CreateEmpty(ctx, in, out)
}
