theme: jekyll-theme-architect

repository: partitio/micro-gateway

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-toc

exclude:
  - run.sh
